### ISSUE TITLE
Support installing by "Formula name"

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#284] opened 2022-02-07 00:34 UTC
Every formula has a unique name, e.g.:
https://github.com/fontist/formulas/blob/508a113f69c1eb635dbb5389d20051ba68fe0037/Formulas/courier_prime.yml#L2

```
name: Courier Prime
```

However it cannot be used for installing:
```sh
$ fontist install -F 'Courier Prime'
Formula 'Courier Prime' not found locally nor available in the Fontist formula repository.
Perhaps it is available at the latest Fontist formula repository.
You can update the formula repository using the command `fontist update` and try again.
```

Currently we only support the formula's filename:

```sh
$ fontist install --formula 'courier_prime'
Downloading font ...
Installing font "courier_prime".
Fonts installed at:
- /Users/user/.fontist/fonts/Courier Prime Bold Italic.ttf
- /Users/user/.fontist/fonts/Courier Prime Bold.ttf
- /Users/user/.fontist/fonts/Courier Prime Italic.ttf
- /Users/user/.fontist/fonts/Courier Prime.ttf
```

**Comment by alexeymorozov** [comment] 2022-02-07 06:23
Before v1.12.0 there were two ways of formula identification: the `name` and `key` attributes.

`name` was taken from formula yaml, and it's uniqueness was not guaranteed.
`key` was extracted from path of a formula, which is unique by design, also it was simpler (all lower-case) and distinst from font name at most cases (e.g. `andale`, `google/noto_sans`, `macos/canela`, `private/metanorma/bsi_gesta`). Cons are it was more machine- or developer-readable.

To simplify and get rid of ambiguity since v1.12.0 there was only the `key` attribute [left](https://github.com/fontist/fontist/commit/cce5057c8ca85920385c0e4c4526ef9cf8195ee9#diff-4dc719be9db47446ae3e3e62c46cfd9c819b5c8e3a4fe82cda09c1ecc94ac6e8L7), though its values were kept in maintained formulas, which seems confusing now.

Do we still need a second way of filtering or identifying formulas?

**Comment by ronaldtse** [comment] 2022-03-05 05:53
@alexeymorozov do we already support this? Thanks!

**Comment by alexeymorozov** [comment] 2022-03-23 13:15
Still don't. There is no `name` attribute currently.

**Comment by alexeymorozov** [comment] 2024-01-22 15:27
I'm going to set unique names for formulas and make `fontist` search by it along with by key.

**Comment by alexeymorozov** [comment] 2024-03-13 14:46
Now it is available in Fontist and described in README:

```
$ fontist install --formula "Courier Prime"
$ fontist install --formula "Google/Noto Sans"
```

Closing.

**Closed by alexeymorozov** 2024-03-13 14:46 UTC
Labels: enhancement
